### ISSUE TITLE
suggested evolution of clustering (use of KNN) to be discussed

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#1]
# Using a "KNN" approach in SimClustering

Actually, SimClustering is computing clusters on all distances matrix computed by NCD. This give good results on coherent alignments in bytes sequences, occuring a large interval of distances values betwwen 0 and 1. Typical coherent alignment is found with text files or DNA sequences.

The problem of misaligned sequences, like pictures is that occurs difficulties to evaluate common parts between sequences with the consequency of computed distances included in a short interval, near from 1. 

One can put the hypothesis that we have very short common parts between two pictures, and this property generates clusters including too much non representative data, corresponding to a noise in measurement.

The idea consists of using just firsts nearest distances in SimClustering, eliminating, by the way, the noise generated by non representative data : this will not increase intervals of distances, but will just compute clusters on really relevant distances.

The other advantage of this KNN use in clusters computing is that SimClustering will work on a reduced set of data.

### NCD
The distances matrix computing program will not be modified.

### PrepClustering

Other parameters will not be changed.

In command line, a parameter ("-k") and a value (the number of retained neighbours) will filter the distances matrix, retaining k+1 firt neighbours. The +1 operation is related to clusters boundaries which are situated between k and k+1 neighborhood of patterns.

PrepClustering will compute triangles where we find :

* vertex1 : current pattern
* vertex2 : first neighbour of vertex1
* vertex3 : first neighbour of vertex2

And 3 segments whose length are distances and joining :

* vertex1-vertex2
* vertex2-vertex3
* vertex3-vertex1

By retaining only k+1 neighbours, we will just write existing triangles in knn intervals. In fact, if vertex3 is not found in filtered matrix, that means that vertex3 and vertex2 (which is, in fact, the k+1 neighbour of vertex1) will not belong to current cluster, because distance represented by vertex3-vertex1 is outside knn limit.

### SimClustering

There is, normally, no modifications to do here. SimClustering will compute Heron's and equilarerality formulas, but on a reduced set of triangles. pattern eliminated by this filter will be considered as singletons.

## Question and remarks to discuss : 

* Are Heron's and equilaterality formulas computed in SimClustering or am I wrong ?
* This evolution should be developed in a "separate branch", because it needs a validation through experience with a large set of data.

**Comment by ChristopheMaldivi** [comment]
![knn_test](https://cloud.githubusercontent.com/assets/7383897/20755840/acc79316-b710-11e6-9826-3834ee271460.png)

@JoelGardes Please find here my test case

**Comment by JoelGardes** [comment]
Could be a better idea to push until more than 3 neighbours ? 
I think that you did'nt notice regression with maximum number of neightours?

**Comment by JoelGardes** [comment]
Deux opérations à faire
- mettre les "orphans" en singleton de suite
- conserver k_nearest_neighbour_threshold (valeur de kppv saisie par l'utilisateur) et effectuer le filtrage de la matrice de distance à k+1

**Comment by JoelGardes** [comment]
Test in progress with consistant results

**Comment by ChristopheMaldivi** [comment]
merged. Open new issue to change behaviour.
