### ISSUE TITLE
Tooling: tool to convert images to our internal RAW image format

### ISSUE THREAD

**Issue by ChristopheMaldivi** [Orange-OpenSource/documentare-simdoc#31]
the tool will be used this way: ```java -jar ImageToRaw.jar -d path/to/input/image/directory```

=> it will generate a ```raw``` output directory which will contain the initial images converted to our raw image file format, ie: image matrix as a byte array, with the '\n' character at the end of each row.

**Comment by JoelGardes** [comment]
OK for this tool. I need remaining : JoTophe markup will be put by Ncd?

**Comment by ChristopheMaldivi** [comment]
Yep

**Comment by ChristopheMaldivi** [comment]
@JoelGardes , please not that I've implemented the following behavior:
 - you provide a directory to the tool
 - the tool will try to convert to raw all files of the directory
 - if OpenCV fails to load the file, a warning is displayed

The following documentation describes the function we use to load the file: http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#imread

At the moment I do not provide any flag to the `imread` method.

**Comment by ChristopheMaldivi** [comment]
**Usage example**

Content of the input directory:
```
$ ls tmp
97_99.png  cincle-plongeur.jpg  documentare-simdoc-1.30.0.tar.bz2  graph.pdf
```

Launch the command:
```
$ java -jar convert-to-raw-1.0-SNAPSHOT.jar  -d tmp

[Convert to Raw - Start]
[WARN] Skip file 'documentare-simdoc-1.30.0.tar.bz2'
[WARN] Skip file 'graph.pdf'
[Convert to Raw - Done]
```

Result in `raw` directory:
```
$ ls raw
97_99.png.raw  cincle-plongeur.jpg.raw
```

So far so good?

**Comment by ChristopheMaldivi** [comment]
Abandoned, this feature was developed in issue #30 : the 'prep-data' tool has a 'raw' option.
