### ISSUE TITLE
continuous integration test: speed up test by cropping source image

### ISSUE THREAD

**Issue by ChristopheMaldivi** [Orange-OpenSource/documentare-simdoc#32]
The test is based on the "anatomie" source image. We suggest to keep only half of the image to speed up the test.

**Comment by JoelGardes** [comment]
If this suggestion was made just to verify I/O and tracking bugs, that's OK for me.

**Comment by ChristopheMaldivi** [comment]
it is just to reduce the integration test duration, but keeping it relevant.

**Comment by JoelGardes** [comment]
So... OK!

**Comment by JoelGardes** [comment]
Linked with dockerization (done on public gitlab)
