### ISSUE TITLE
[Question] time consuming with NCD on our raw format

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#34]
Do you have any estimation on the time consuming increase of NCD due to raw format choose compared to png ? (not so important question, but a good indice for use definitions)

**Comment by ChristopheMaldivi** [comment]
+25%, to be adjusted by a simple test:
 - line-detection on anatomie for instance
 - then ncd only on png -> write down the elapsed time
 - idem with raw
 - then compare

**Comment by JoelGardes** [comment]
OK, less critical than I feared
