### ISSUE TITLE
problem with thumbnails from PDF files

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#39]
[Thumbnails - Start]
Can not create thumbnail, provided image '/Users/jyig5563/Desktop/plib/./pdf/1Is6Kqopl9ErAdhgrS9R8eXAWm0zZz.PDF' is invalid
Niels:plib jyig5563$ 

guilty file joined

[1hmzZzIxvPcKymqyDBZx6avrXnO3wzZz.PDF](https://github.com/Orange-OpenSource/documentare-simdoc/files/783308/1hmzZzIxvPcKymqyDBZx6avrXnO3wzZz.PDF)

**Comment by ChristopheMaldivi** [comment]
Opencv does not support pdf... we are donkeys...
I need to revert the thumbnails tool so that it will still rely on convert, just for the pdf.

**Comment by JoelGardes** [comment]
We should make a review of thumbnail tool (Christophe and Jo)

**Comment by JoelGardes** [comment]
issue #42
