### ISSUE TITLE
[enhancement] suggestion for options in command lines

### ISSUE THREAD

**Issue by JoelGardes** [Orange-OpenSource/documentare-simdoc#9]
# Need of harmonization in naming options in command lines

to be discussed.

## LineDetection

no option -> can be maintained 
[possible upcoming enhancement allowing to input a directory of pictures ou a multipage picture]

## NCD

-file1 and -file2 -> change to -d1 and -d2 
[possible upcoming enhancement allowing to compare a file with a directory or two files]
-simDocJsonGz -> change to -simdoc
-help -> change to -h or -help indifferently

## PrepClustering

-f -> change to -json (what need this parameter? a compressed json file!)
-help -> change to -h or -help indifferently

## SimClustering

-h -> change to -h or -help indifferently
-i -> change to -json 
-simDocJsonGz -> change to -simdoc
-scut and -sdScut -> change -scut as optional parameter with optional standard deviation value (default 2)
-ccut and -tileCcut -> change to -ccut as optional parameter with optional quantile value (default 75)
-sdArea -> change to -sdarea as optional parameter with optional value (default 2)
-sdQ -> change to -sdq as optional parameter with optional value (default 2) <- previous mismatch typing value 3 (sorry!)
[explanation : use of KNN allows to avoid Area and equilaterality computing with a short value of k]

## Graph
-h -> change to -h or -help indifferently
-i -> change to -json

**Comment by ChristopheMaldivi** [comment]
Met difficulties with apache commons-cli optional arg feature, see bug here: https://issues.apache.org/jira/browse/CLI-265

Use 1.4-SNAPSHOT version to fix it. Not perfect, we should upgrade to 1.4 as soon as it will be into the wild.

So far so good.

**Comment by JoelGardes** [comment]
Syntaxes reviewed OK, to be tested in large area.
